# cfn/security.yaml
AWSTemplateFormatVersion: "2010-09-09"
Description: Security stack (Security Groups + IAM role/profile for EC2 using SSM/CloudWatch)

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  AppPort:
    Type: Number
    Default: 5000

Resources:
  AlbSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ALB SG - allow HTTPS from internet
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      Tags: [{Key: Name, Value: alb-sg}]

  AppSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: App SG - allow only ALB to app port
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref AppPort
          ToPort: !Ref AppPort
          SourceSecurityGroupId: !Ref AlbSG
      Tags: [{Key: Name, Value: app-sg}]

  DbSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: DB SG - allow only App SG on 3306
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref AppSG
      Tags: [{Key: Name, Value: db-sg}]

  AppRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub student-portal-ec2-role-${AWS::StackName}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        # SSM (no SSH needed), CloudWatch agent logs/metrics
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy

  AppInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub student-portal-ec2-profile-${AWS::StackName}
      Roles: [!Ref AppRole]

Outputs:
  AlbSecurityGroupId:
    Value: !Ref AlbSG
  AppSecurityGroupId:
    Value: !Ref AppSG
  DbSecurityGroupId:
    Value: !Ref DbSG
  InstanceProfileName:
    Value: !Ref AppInstanceProfile
